# Generated by Django 3.2.4 on 2021-06-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCelular', models.CharField(max_length=15, verbose_name='Numero de Telefono')),
                ('nombre', models.CharField(max_length=75, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=75, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=254, verbose_name='Email')),
                ('imagenContacto', models.ImageField(blank=True, null=True, upload_to='contactos', verbose_name='Foto Perfil')),
            ],
        ),
    ]
